#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

"""
ABOUT: This is the main entry for the LOGAN (whole genome sequencing pipeline).
REQUIRES:
  - python>=3.5
  - nextflow  
  - singularity
DISCLAIMER:
                    PUBLIC DOMAIN NOTICE
        CCR Collaborative Bioinformatics Resource (CCBR)
                National Cancer Institute (NCI)
This software/database is a "United  States Government Work" under
the terms of the United  States Copyright Act.  It was written as 
part of the author's official duties as a United States Government
employee and thus cannot be copyrighted. This software is freely
available to the public for use.
Although all  reasonable  efforts have been taken  to ensure  the
accuracy and reliability of the software and data, CCBR do not and
cannot warrant the performance or results that may  be obtained by 
using this software or data. CCBR and NCI disclaim all warranties,
express  or  implied,  including   warranties   of   performance, 
merchantability or fitness for any particular purpose.
Please cite the author and the "NIH Biowulf Cluster" in any work or
product based on this material.


    PIPELINE TYPE
    Align --PIPE_ALIGN-TRIM ALIGN
    Variant Calls--PIPE_VC-Variant calling step after align
    Germline Calls DV--PIPE_GERMLINE-Germline after align
    QC requires Alignment, Germline--PIPE_QC--After everything
    --PIPE_BAMVC-BAM variant calling only
    --PIPE_TONLY_TRIM-Trim and Align
    --PIPE_TONLY_TRIM-Trim and Align
"""

import argparse, os, time, sys, subprocess, re, json

def parse_args():
    parser = argparse.ArgumentParser(description='Input files')
    parser.add_argument('--fastq',help='FQ Inputs')
    parser.add_argument('--filelist',help="Files input")
    parser.add_argument('--bam',help="Files input")
    parser.add_argument('--mode',help='Modes (align, variant call, SV)')
    parser.add_argument('--paired',help='Paired',action="store_true")
    parser.add_argument('--splitregions',default=24,help="How splits per regions")
    parser.add_argument('--sv',help="Add Structural VC calling",action="store_true")
    parser.add_argument('--output',help="Output Directory")
    parser.add_argument('--genome',help="hg38 or mm10")
    parser.add_argument('--sample_sheet',help="Sample sheet")
    parser.add_argument('--profile',help="Biowulf or Local Run")
    parser.add_argument('--resume',action="store_true",default="True",help="Resume previous run?")
    parser.add_argument('--submit',action="store_true",help="Submit to SLURM?")
    parser.add_argument('--stub',action="store_true",help="Stub run")
    args = parser.parse_args()
    return(args)


    
def main():
    args=parse_args()
    dirname = os.path.dirname(os.path.realpath(__file__))
    outdirname = os.path.basename(os.getcwd())
    c1="#!/usr/bin/bash"
    c2="module load nextflow"
    c3="module load singularity"
    #Paired Mode-> either align/VC/germline with FASTQ
    if args.paired and args.sample_sheet:
        sample_path="--sample_sheet '"+args.sample_sheet+"'"
        if args.mode=="align":
            mode="--PIPE_ALIGN"
        elif args.mode=="vc" and args.sv:
            mode="--PIPE_SV"
        elif args.mode=="vc":
            mode="--PIPE_VC"
        elif args.mode=="germline":
            mode="--PIPE_GERMLINE"
        elif args.mode=="qc":
            mode="--PIPE_QC"
        if args.fastq:
            in1="--fastq_input '"+args.fastq+"'"
        elif args.filelist:
            in1="--file_input "+args.filelist
        elif args.bam:
            in1="--bam "+args.bam
        else:
            print("Missing sample sheet for paired mode or you would like Tumor only mode?")
    else:
    #Tumor Only- fastq only
        if args.mode=="align":
            mode="--PIPE_TONLY_ALIGN"
            sample_path=""
            if args.fastq:
                in1="--fastq_input '"+args.fastq+"'"
            elif args.filelist:
                in1="--file_input "+args.filelist
        if args.mode=="vc":
            sample_path=""
            if args.fastq:
                mode="--PIPE_TONLY_VC"
                in1="--fastq_input '"+args.fastq+"'"
            elif args.bam:
                mode="--PIPE_TONLY_BAMVC"
                in1="--bam_input '"+args.bam+"'"
            elif args.filelist:
                mode="--PIPE_TONLY_BAMVC"
                in1="--file_input "+args.filelist
        if args.mode=="qc":
            sample_path=""
            if args.fastq:
                mode="--PIPE_TONLY_QC"
                in1="--fastq_input '"+args.fastq+"'"
            elif args.bam:
                mode="--PIPE_TONLY_QC"
                in1="--bam_input '"+args.bam+"'"
    if (args.stub and args.profile is None): 
        profile="-profile localstub"
    elif args.profile=="local":
        profile="-profile local"
    elif (args.profile=="biowulf" or args.profile is None):
        profile="-profile biowulf"
    if args.resume:
        resume="-resume"
    else:
        resume=""
    c4=["nextflow run",dirname + '/main.nf',"-c "+ dirname +"/nextflow.config",
        in1,profile,resume,sample_path,mode,
        "--genome",args.genome,
        "--output '" +args.output+"'"+" --split_regions " +str(args.splitregions)]
    cmd1=' '.join(c4)
    code=c1+"\n"+c2+"\n"+c3+"\n"+cmd1
    time1=time.strftime("%Y_%m_%d_%H%M%S")
    #outswarmmut='wgs_nf_'+time1+'.slurm'
    outswarmmut=args.output+"_"+time1+'.slurm'
    with open(outswarmmut, "a") as outfile:
        outfile.write(code+"\n")
    sbatch_mut="sbatch --cpus-per-task=2 --mem=16g --time 10-00:00:00 --partition norm --output submit_"+time1+".log --error error_"+time1+".log --mail-type=BEGIN,TIME_LIMIT_90,END "+outswarmmut 
    if args.stub:
        cmd2=cmd1+" --split_regions 4 -stub -without-podman T -without-conda -without-docker"
        print(cmd2)
        os.system(cmd2)
    elif args.submit:
        print(sbatch_mut)
        os.system(sbatch_mut)
    else:
        sbatch_out='run_sbatch'+time1+'.sh'
        with open(sbatch_out, "a") as outfile:
            outfile.write(sbatch_mut+"\n")
        print(sbatch_mut)
if __name__=="__main__":
  main()

