site_name: CCBR LOGAN
site_description: >-
  CCBR LOGAN-whoLe genOme-sequencinG Analysis pipeliNe
nav:
  - Home: 'index.md'
  - Pipeline:
    - Tumor-Normal:  'user-guide/pipeline.md'
theme:
    name: readthedocs
    highlightjs: true