site_name: CCBR LOGAN
site_description: >-
  CCBR Whole Genome Sequencing Pipeline 
nav:
  - Home: 'index.md'
  - Pipeline:
    - Tumor-Normal:  'user-guide/pipeline.md'
theme:
    name: readthedocs
    highlightjs: true