site_name: CCBR LOGAN
site_description: >-
  CCBR Whole Genome Sequencing Pipeline 
nav:
  - Home: 'index.md'
  - Pipeline:
    - Tumor-Normal: 'user-guide/pipeline.md'
  - Tools:
    - Comparisons: 'user-guide/tool_comparisons.md'
theme:
    name: readthedocs
    highlightjs: true