site_name: CCBR LOGAN
site_url: https://ccbr.github.io/LOGAN
site_description: >-
  CCBR whoLe genOme-sequencinG Analysis pipeliNe (LOGAN)
nav:
  - Home: 'index.md'
  - Pipeline:
    - Tumor-Normal: 'user-guide/pipeline.md'
  - Tools:
    - Comparisons: 'user-guide/tool_comparisons.md'
theme:
    name: readthedocs
    highlightjs: true
extra:
  version:
    provider: mike