name: docs
# this workflow requires:
#  - an mkdocs config file (`mkdocs.yml`)
#  - website dependencies in `docs/requirements.txt`
on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "**.md"
      - .github/workflows/docs-mkdocs.yml
      - mkdocs.yml
permissions:
  contents: write
  pages: write
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - uses: CCBR/actions/mkdocs-mike@v0.1
        with:
          github-token: ${{ github.token }}
